wandb: Currently logged in as: _cloud (ml-nyush). Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: /home/hy2611/.netrc
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ext3/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
wandb: - Waiting for wandb.init()...    cli.cli(prog_name="python -m wandb")
  File "/ext3/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/ext3/miniconda3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ext3/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ext3/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/cli/cli.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/cli/cli.py", line 280, in service
    server.serve()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
    mux.loop()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 428, in loop
    raise e
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 426, in loop
    self._loop()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 419, in _loop
    self._process_action(action)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 381, in _process_action
    self._process_add(action)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 223, in _process_add
    stream.start_thread(thread)
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 80, in start_thread
    self._wait_thread_active()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 85, in _wait_thread_active
    assert result
AssertionError
wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...Namespace(dataset='cifar100', root='../dataset/', arch='resnet32', num_classes=100, imbalance_rate=1.0, lr=0.01, epochs=200, batch_size=64, momentum=0.9, weight_decay=0.005, resample_weighting=0.0, label_weighting=1.0, contrast_weight=10, beta=0.5, loss='ce', eps=0.05, etf_cls=False, mixup=0, mixup_alpha=0.2, seed=3407, print_freq=1000, gpu=0, workers=4, resume=None, start_epoch=0, root_model='./output/', store_name='cifar100_resnet32/1.0/ce_mx0a0.2', debug=10, knn=False)
creating folder ./output/cifar100_resnet32/1.0/ce_mx0a0.2
Problem at: /scratch/hy2611/GLMC/main_wb.py 60 main
wandb: ERROR Run initialization has timed out after 90.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/scratch/hy2611/GLMC/main_wb.py", line 210, in <module>
    main(args)
  File "/scratch/hy2611/GLMC/main_wb.py", line 60, in main
    wandb.init(project="Cifar10_mx0_a_diff",
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    raise e
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/ext3/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
slurmstepd: error: *** JOB 41071508 ON gr017 CANCELLED AT 2023-12-22T00:01:21 ***
